<?php
/**
 * Created by PhpStorm.
 * User: Jinping<jinping_125@qq.com>
 * Date: 2017/3/15
 * Time: 17:25
 */

namespace App\Http\Controllers\Admin\Base;


use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Cookie;

class BaseController extends Controller
{
    protected $userInfo;
    public function __construct()
    {
        parent::__construct();
        if($auth = Cookie::get("user_auth")){
            if($auth = decrypt($auth)){
                $this->userInfo = json_decode($auth)?json_decode($auth):null;
            }
        }

    }

    //重写试图显示方法
    protected function view($template = null, $data = [], $mergeData = [])
    {
        $data["loginUserInfo"] = null;
        $data["currentRoute"] = \Request::path();
        if($auth = Cookie::get("user_auth")){
            $auth = json_decode($auth);
            if(isset($auth->user_id) && $auth->user_id > 0){
                $data["loginUserInfo"] = $auth;
            }
        }
        return parent::view($template, $data, $mergeData); // TODO: Change the autogenerated stub
    }
    /**
     * sql分页操作
     *
     * @param array $query
     * @param array $array
     * @return array
     */
    function querySqlPageData($sql , $array = array("pre_page" => PERPAGE , "is_sql" => false, "mode" => 1)){
        $list = array();
        extract ( $array );
        if(!$pre_page) $pre_page = PERPAGE ;
        $result = $this->db->Execute($sql);
        $total_cnt = 0;
        foreach($result as $k=>$v){
            $total_cnt++;
        }
        //分页风格
        $mode = $mode ? $mode : 1;
        $page_html = multiPages($total_cnt , $pre_page, $mode);
        $limit = buildLimit($total_cnt , $pre_page);
        $sql .= " limit " . $limit;
        $res = $this->db->Execute($sql);
        $list = $res ? $res->getArray() : array();
        return array('ph' => $page_html , "list" => $list , "total" => $total_cnt);
    }
}